### ISSUE TITLE
Interface tracker

### ISSUE THREAD

**Issue by oir** [oir/startle#23]
- [ ] single entry from a function
- [ ] multiple commands from multiple functions
- [ ] multiple commands from a class, a la Fire?
- [ ] parse into a dataclass a la HFArgParser
